"""
Step-by-step learning system that guides students through topics progressively.
Each step builds on the previous one, with questions and feedback.
"""

from typing import List, Dict, Any, Optional
from dataclasses import dataclass, field
from enum import Enum
from datetime import datetime


class StepType(Enum):
    """Types of learning steps."""
    INTRODUCTION = "introduction"
    QUESTION = "question"
    EXPLANATION = "explanation"
    EXAMPLE = "example"
    PRACTICE = "practice"
    VERIFICATION = "verification"
    SUMMARY = "summary"


class StepStatus(Enum):
    """Status of a learning step."""
    NOT_STARTED = "not_started"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    NEEDS_REVIEW = "needs_review"


@dataclass
class LearningStep:
    """Represents a single step in the learning journey."""
    step_number: int
    step_type: StepType
    content: str
    question: Optional[str] = None
    expected_answer: Optional[str] = None
    hints: List[str] = field(default_factory=list)
    multimedia: List[Dict[str, str]] = field(default_factory=list)
    status: StepStatus = StepStatus.NOT_STARTED
    student_answer: Optional[str] = None
    feedback: Optional[str] = None
    attempts: int = 0
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            "step_number": self.step_number,
            "step_type": self.step_type.value,
            "content": self.content,
            "question": self.question,
            "hints": self.hints,
            "multimedia": self.multimedia,
            "status": self.status.value,
            "attempts": self.attempts
        }


@dataclass
class LearningPath:
    """Represents a complete learning path for a topic."""
    topic: str
    total_steps: int
    current_step: int = 0
    steps: List[LearningStep] = field(default_factory=list)
    started_at: datetime = field(default_factory=datetime.now)
    completed_at: Optional[datetime] = None
    
    def get_current_step(self) -> Optional[LearningStep]:
        """Get the current step."""
        if 0 <= self.current_step < len(self.steps):
            return self.steps[self.current_step]
        return None
    
    def advance_step(self) -> bool:
        """Move to next step. Returns True if advanced, False if at end."""
        if self.current_step < len(self.steps) - 1:
            self.current_step += 1
            return True
        return False
    
    def get_progress_percentage(self) -> float:
        """Get learning progress as percentage."""
        if not self.steps:
            return 0.0
        completed = sum(1 for step in self.steps if step.status == StepStatus.COMPLETED)
        return (completed / len(self.steps)) * 100
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            "topic": self.topic,
            "total_steps": self.total_steps,
            "current_step": self.current_step,
            "progress_percentage": self.get_progress_percentage(),
            "steps": [step.to_dict() for step in self.steps]
        }


class StepByStepLearning:
    """Manages step-by-step learning journeys."""
    
    def __init__(self):
        """Initialize the step-by-step learning manager."""
        self.active_paths: Dict[str, LearningPath] = {}
    
    def create_learning_path(self, topic: str, difficulty: str = "intermediate") -> LearningPath:
        """
        Create a structured learning path for a topic.
        
        Args:
            topic: The topic to learn
            difficulty: Difficulty level
            
        Returns:
            LearningPath object
        """
        # This will be generated by AI, but here's the structure
        path = LearningPath(
            topic=topic,
            total_steps=0  # Will be set when steps are generated
        )
        
        return path
    
    def generate_next_step(
        self,
        path: LearningPath,
        previous_answer: Optional[str] = None
    ) -> Optional[LearningStep]:
        """
        Generate the next step based on current progress.
        
        Args:
            path: Current learning path
            previous_answer: Student's answer to previous step
            
        Returns:
            Next learning step or None if path is complete
        """
        current = path.get_current_step()
        
        # If there's a previous answer, evaluate it first
        if previous_answer and current:
            self._evaluate_answer(current, previous_answer)
            
            # If answer was wrong and attempts < 3, give hint and retry
            if current.status == StepStatus.NEEDS_REVIEW and current.attempts < 3:
                return self._create_hint_step(current)
            
            # Mark as completed and move to next
            current.status = StepStatus.COMPLETED
            if not path.advance_step():
                # Path completed
                path.completed_at = datetime.now()
                return None
        
        # Get next step
        return path.get_current_step()
    
    def _evaluate_answer(self, step: LearningStep, answer: str):
        """Evaluate student's answer to a step."""
        step.student_answer = answer
        step.attempts += 1
        
        # Simple evaluation (in real implementation, use AI)
        if step.expected_answer:
            # Check if answer is close to expected
            if self._is_answer_correct(answer, step.expected_answer):
                step.status = StepStatus.COMPLETED
                step.feedback = "Correct! Well done!"
            else:
                step.status = StepStatus.NEEDS_REVIEW
                step.feedback = "Not quite. Let me give you a hint."
        else:
            # No expected answer, mark as completed
            step.status = StepStatus.COMPLETED
    
    def _is_answer_correct(self, answer: str, expected: str) -> bool:
        """Check if answer is correct (simplified)."""
        # In real implementation, use AI to evaluate
        answer_lower = answer.lower().strip()
        expected_lower = expected.lower().strip()
        return answer_lower in expected_lower or expected_lower in answer_lower
    
    def _create_hint_step(self, original_step: LearningStep) -> LearningStep:
        """Create a hint step for a question the student got wrong."""
        hint_index = min(original_step.attempts - 1, len(original_step.hints) - 1)
        hint = original_step.hints[hint_index] if original_step.hints else "Think about it differently."
        
        return LearningStep(
            step_number=original_step.step_number,
            step_type=StepType.QUESTION,
            content=f"Hint: {hint}\n\nLet's try again: {original_step.question}",
            question=original_step.question,
            expected_answer=original_step.expected_answer,
            hints=original_step.hints,
            status=StepStatus.IN_PROGRESS
        )


def generate_learning_path_prompt(topic: str, difficulty: str = "intermediate") -> str:
    """
    Generate a prompt to create a step-by-step learning path.
    
    Args:
        topic: The topic to create a path for
        difficulty: Difficulty level
        
    Returns:
        Formatted prompt for AI
    """
    prompt = f"""Create a STEP-BY-STEP learning path for: {topic}
Difficulty level: {difficulty}

IMPORTANT: Break down the topic into small, manageable steps. Each step should:
1. Build on the previous step
2. Include ONE question or concept at a time
3. Be interactive and engaging
4. Include multimedia when helpful

Generate a JSON structure with 7-10 steps following this format:

{{
  "topic": "{topic}",
  "difficulty": "{difficulty}",
  "estimated_time": "20-30 minutes",
  "steps": [
    {{
      "step_number": 1,
      "step_type": "introduction",
      "content": "Brief introduction to the topic",
      "multimedia": [
        {{"type": "image", "description": "overview diagram"}}
      ]
    }},
    {{
      "step_number": 2,
      "step_type": "question",
      "content": "Before we dive in, let me check what you already know.",
      "question": "What do you think [topic] means?",
      "hints": [
        "Think about [hint 1]",
        "Consider [hint 2]"
      ]
    }},
    {{
      "step_number": 3,
      "step_type": "explanation",
      "content": "Here's what [topic] actually is...",
      "multimedia": [
        {{"type": "image", "description": "detailed diagram"}},
        {{"type": "video", "query": "topic explanation"}}
      ]
    }},
    {{
      "step_number": 4,
      "step_type": "question",
      "content": "Now let's check your understanding.",
      "question": "Based on what you learned, can you explain [concept]?",
      "expected_answer": "Brief description of correct answer",
      "hints": ["hint 1", "hint 2"]
    }},
    {{
      "step_number": 5,
      "step_type": "example",
      "content": "Let's see a real-world example...",
      "multimedia": [
        {{"type": "interactive", "description": "hands-on activity"}}
      ]
    }},
    {{
      "step_number": 6,
      "step_type": "practice",
      "content": "Now it's your turn to try!",
      "question": "Solve this problem: [problem]",
      "expected_answer": "correct solution",
      "hints": ["step 1", "step 2"]
    }},
    {{
      "step_number": 7,
      "step_type": "verification",
      "content": "Let's verify you truly understand.",
      "question": "Can you apply this to a new scenario: [scenario]?",
      "expected_answer": "expected application"
    }},
    {{
      "step_number": 8,
      "step_type": "summary",
      "content": "Great job! Here's what you learned: [summary]",
      "multimedia": [
        {{"type": "image", "description": "summary infographic"}}
      ]
    }}
  ]
}}

STEP TYPES TO USE:
- introduction: Introduce the topic
- question: Ask a question (wait for answer before proceeding)
- explanation: Explain a concept with multimedia
- example: Show real-world examples
- practice: Give practice problems
- verification: Test true understanding
- summary: Summarize what was learned

RULES:
1. Each step should be SHORT (2-3 sentences max)
2. Questions should be SPECIFIC and have clear answers
3. Include multimedia suggestions using types: image, video, wolfram, audio, interactive
4. Provide 2-3 hints for each question
5. Build progressively - each step assumes previous steps are understood
6. Make it INTERACTIVE - lots of questions, not just explanations

Generate the complete learning path now as valid JSON."""
    
    return prompt


def generate_step_response_prompt(
    step: LearningStep,
    student_answer: Optional[str] = None,
    is_correct: Optional[bool] = None
) -> str:
    """
    Generate a prompt for responding to a student at a specific step.
    
    Args:
        step: Current learning step
        student_answer: Student's answer (if any)
        is_correct: Whether the answer was correct (if evaluated)
        
    Returns:
        Formatted prompt for AI
    """
    if step.step_type == StepType.QUESTION and student_answer:
        # Evaluate answer and provide feedback
        if is_correct:
            prompt = f"""The student answered this question correctly:

Question: {step.question}
Student's answer: {student_answer}

Provide:
1. Enthusiastic praise (2-3 sentences)
2. Brief explanation of why their answer is correct
3. One interesting related insight
4. Transition to next step: "Ready for the next step?"

Keep it encouraging and concise!"""
        else:
            # Wrong answer - provide hint
            hint_num = min(step.attempts, len(step.hints))
            prompt = f"""The student answered this question incorrectly:

Question: {step.question}
Student's answer: {student_answer}
Expected answer: {step.expected_answer}
Attempt number: {step.attempts}

Provide:
1. Encouraging response: "Not quite, but good try!"
2. Identify the specific misconception
3. Give hint #{hint_num}: {step.hints[hint_num-1] if hint_num <= len(step.hints) else 'Think about it from a different angle'}
4. Ask them to try again

Stay positive and supportive!"""
    
    elif step.step_type == StepType.INTRODUCTION:
        prompt = f"""Present this introduction step:

{step.content}

Make it engaging and exciting! Include:
1. Hook to grab attention
2. Why this topic is interesting/useful
3. What they'll learn
4. Multimedia suggestions from: {step.multimedia}

End with: "Let's start with step 1!"

Keep it brief (3-4 sentences) and enthusiastic!"""
    
    elif step.step_type == StepType.EXPLANATION:
        prompt = f"""Present this explanation step:

{step.content}

Provide:
1. Clear, concise explanation
2. Use multimedia: {step.multimedia}
3. Real-world analogy or example
4. Check understanding: "Does this make sense so far?"

Keep it focused and include multimedia tags like [IMAGE: ...], [VIDEO: ...]"""
    
    elif step.step_type == StepType.EXAMPLE:
        prompt = f"""Present this example step:

{step.content}

Provide:
1. Concrete, relatable example
2. Walk through it step-by-step
3. Use multimedia: {step.multimedia}
4. Ask: "Can you see how this works?"

Make the example vivid and memorable!"""
    
    elif step.step_type == StepType.PRACTICE:
        prompt = f"""Present this practice step:

{step.content}
Question: {step.question}

Provide:
1. Brief setup (1-2 sentences)
2. Clear practice problem or exercise
3. Encourage them to try: "Give it a shot!"

Wait for their answer before proceeding."""
    
    elif step.step_type == StepType.VERIFICATION:
        prompt = f"""Present this verification step:

{step.content}
Question: {step.question}

This is the final check! Provide:
1. Context: "Let's see if you can apply what you learned"
2. The verification question
3. Encourage deep thinking

This tests true understanding, not just memorization."""
    
    elif step.step_type == StepType.SUMMARY:
        prompt = f"""Present this summary step:

{step.content}

Provide:
1. Celebrate their completion! 🎉
2. Summarize key points learned (3-5 bullet points)
3. Use multimedia: {step.multimedia}
4. Suggest next topics to explore
5. Encourage continued learning

Make them feel accomplished!"""
    
    else:
        prompt = f"""Present this step:

{step.content}

Keep it clear, engaging, and appropriate for the step type: {step.step_type.value}"""
    
    return prompt


def generate_next_question_prompt(
    topic: str,
    previous_steps: List[LearningStep],
    current_understanding: str
) -> str:
    """
    Generate a prompt to create the next question in the learning sequence.
    
    Args:
        topic: The topic being learned
        previous_steps: Steps completed so far
        current_understanding: Assessment of student's current understanding
        
    Returns:
        Formatted prompt for generating next question
    """
    steps_summary = "\n".join([
        f"Step {s.step_number} ({s.step_type.value}): {s.content[:100]}..."
        for s in previous_steps[-3:]  # Last 3 steps
    ])
    
    prompt = f"""Generate the NEXT STEP in learning: {topic}

Previous steps completed:
{steps_summary}

Current understanding level: {current_understanding}

Generate ONE next step that:
1. Builds on what they've learned
2. Introduces ONE new concept or question
3. Is appropriately challenging
4. Includes multimedia if helpful
5. Checks understanding before moving forward

Return as JSON:
{{
  "step_number": {len(previous_steps) + 1},
  "step_type": "question|explanation|example|practice",
  "content": "Brief content (2-3 sentences)",
  "question": "Specific question if step_type is question or practice",
  "expected_answer": "What a correct answer should include",
  "hints": ["hint 1", "hint 2"],
  "multimedia": [
    {{"type": "image|video|wolfram|interactive", "description": "what to show"}}
  ]
}}

Make it interactive and engaging!"""
    
    return prompt
